//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDevSystem.Portals.Admin_Portal.IT_Admin_Portal.Applicant
{


    public partial class ViewApplicantsAdmin
    {
    }
}
